---
- name: Revert system to original state
  hosts: webservers
  tasks:
    - name: Install Apache
      apt:
        name: apache2
        state: present

    - name: Start Apache Service
      service:
        name: apache2
        state: started

    - name: Ensure correct ownership and permissions for index.html
      file:
        path: /var/www/html/index.html
        owner: www-data
        group: www-data
        mode: '0644'
