---
dependency:
  name: galaxy
  options:
    requirements-file: requirements.yml
driver:
  name: docker
lint: |
  set -e
  yamllint .
  ansible-lint
platforms:
  - name: molecule-ubuntu
    image: ubuntu:latest
provisioner:
  name: ansible
verifier:
  name: ansible