dependency:
  name: galaxy
  options:
    requirements-file: requirements.yml
driver:
  name: docker
lint: |
  set -e
  yamllint .
  ansible-lint
platforms:
# FOUND_SYSTEMS #
provisioner:
  name: ansible
verifier:
  name: ansible